### ISSUE TITLE
Use fat arrow function and ES2015+ class properties for binding to methods of React class 

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/webpack-babel-react#1]
I want to be able to use fat arrow functions for method declaration in this boilerplate, but receive the following error when trying to do so:

```javascript
ERROR in ./src/js/app.js
Module build failed: SyntaxError: Unexpected token (5:6)

  3 |
  4 | export default class App extends Component {
> 5 |   dog = () => {
    |       ^
  6 |     console.log('hey doggy dog');
  7 |   }
```

A good example of what I want is listed in [Method 4](http://egorsmirnov.me/2015/08/16/react-and-es6-part3.html) of this article

Acceptance Criteria:
***EDIT***: Removed stage-0 criteria
1. Application starts on the `yarn dev` command with no errors.

**Comment by andrewgreenh** [comment]
I'd like to take a shot but are you really sure you want stage-0?  Stage-0 includes many features that are far from stable. I'd recommend using the plugin babel-plugin-transform-class-properties and babel-preset-env + state-3. This way you only have very stable elements, as Class fields is already stage-3 (but not in the preset)

**Comment by BlakeGuilloud** [comment]
@andreasgruenh I am open to that!
