### ISSUE TITLE
Proper production bundle

### ISSUE THREAD

**Issue by andrewgreenh** [BlakeGuilloud/webpack-babel-react#4]
As this is a starter project/boiler plate, would it be useful to add a proper production task? It should do 2 important things: Minify the build (uglify or babili?) and it should set the correct NODE_ENV, so that the react production build is used.

If you think that this is useful, I'd like to implement it :)

**Comment by BlakeGuilloud** [comment]
@andreasgruenh Absolutely- it's all yours! Thanks

**Comment by BlakeGuilloud** [comment]
Thanks for the work on this!
